# -*- coding: utf-8 -*-
"""Process_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NHb5S1Fdt-jznz6l4hQHX3q45ZmYfAmz
"""

import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('gastr.csv')

dataset.shape

dataset = dataset.drop_duplicates(subset=['current_block_number'])

dataset=dataset.reset_index(drop=True)

# j=0
# for i in range (0,len(dataset)):
#   if dataset['pending_trx_last_1H_AVG:'][i]=="(Average)":
#     print("a")
#     j=j+1
#     dataset['pending_trx_last_1H_AVG:'][i]=dataset['pending_trx_last_1H_AVG:'][i+1]
# print(j)  
# j=0
# for i in range (0,len(dataset)):
#     a = str(dataset['pending_trx_last_1H_AVG:'][i])
#     a = a[:3] + ',' + a[3:]
#     dataset['pending_trx_last_1H_AVG:'][i] = a
#     print(a)

# dataset['current_block_nbr:'] = dataset.pop('current_block_nbr')

# dataset.insert(0, 'current_block_nbr', dataset.pop('current_block_nbr:'))

# dataset['pending_trx_last_1H_AVG:'] = dataset['pending_trx_last_1H_AVG:'].str.replace(',', '.')

# dataset['pending_trx_last_1H_AVG:'] = dataset['pending_trx_last_1H_AVG:'].astype(float)

# dataset['current_block_nbr'] = dataset['current_block_nbr'].astype(int)

dataset= dataset.sort_values(by='current_block_number')

dataset=dataset.reset_index(drop=True)

# dataset = dataset.rename(columns={'dernier_block_nbr': 'current_block_nbr'})

from datetime import datetime, timedelta

for i in range(0,len(dataset['current_datetime'])):
    # parse the current datetime string using strptime
    dt = datetime.strptime(str(dataset['current_datetime'][i]), '%Y-%m-%d %H:%M:%S')
    new_time =dt - timedelta(hours=1)
    # convert the datetime object to a new datetime string format using strftime
    dataset['current_datetime'][i] = new_time.strftime("%Y-%m-%d %H:%M:%S")

df_info.index = pd.to_datetime(df_info['current_datetime'], format='%d.%m.%Y %H:%M:%S')

# from datetime import datetime, timedelta

# for i in range(4290,len(dataset['current_datetime'])):
#     # parse the current datetime string using strptime
#     dt = datetime.strptime(str(dataset['current_datetime'][i]), '%Y-%m-%d %H:%M:%S')
#     new_time =dt - timedelta(hours=1)
#     # convert the datetime object to a new datetime string format using strftime
#     dataset['current_datetime'][i] = new_time.strftime("%Y-%m-%d %H:%M:%S")

# dataset=dataset[23924:]

dataset.to_csv("DATAPRICE.csv", index=False)
# Import the necessary libraries

from google.colab import files

# Download the file to your local machine
files.download('DATAPRICE.csv')